from typing import Sequence, overload

class DType:
    F32: int
    F16: int
    BF16: int
    Q8_0: int

class Device:
    CPU: int
    CUDA: int

float32: DType
f16: DType
bf16: DType
q8_0: DType

class Tensor:
    def __init__(
        self,
        shape: Sequence[int],
        dtype: DType = ...,
        device: Device = ...,
    ) -> None: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def device(self) -> Device: ...
    def numel(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def has_storage(self) -> bool: ...
    def is_contiguous(self) -> bool: ...
    def data(self) -> bytes: ...
    def reshape(self, dims: Sequence[int]) -> "Tensor": ...
    def view(self, dims: Sequence[int]) -> "Tensor": ...
    def transpose(self, dim0: int, dim1: int) -> "Tensor": ...
    @property
    def T(self) -> "Tensor": ...
    @property
    def mT(self) -> "Tensor": ...
    def contiguous(self) -> "Tensor": ...

def empty(
    shape: Sequence[int],
    dtype: DType = ...,
    device: Device = ...,
) -> Tensor: ...
def zeros(
    shape: Sequence[int],
    dtype: DType = ...,
    device: Device = ...,
) -> Tensor: ...
def ones(
    shape: Sequence[int],
    dtype: DType = ...,
    device: Device = ...,
) -> Tensor: ...
def nbytes(numel: int, dtype: DType) -> int: ...
def itemsize(dtype: DType) -> int: ...
def execute(output: Tensor) -> None: ...
