function(kiln_print_summary)
  message(STATUS "")
  message(STATUS "======= KILN CONFIGURATION ==========")
  message(STATUS "  Version:         ${PROJECT_VERSION}")
  message(STATUS "  Build type:      ${CMAKE_BUILD_TYPE}")
  message(STATUS "  Compiler:        ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "  Build Python:    ${KILN_BUILD_PYTHON}")
  message(STATUS "  Build tests:     ${KILN_BUILD_TESTS}")
  message(STATUS "========================================")
  message(STATUS "")
endfunction()
